version: '3.3'

volumes:
  pg_data:
  static:
  frontend_volume:
  media_volume:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: shunyabo/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media_volume:/app/media/
      - ../data/:/app/static/data/

  frontend:
    image: shunyabo/foodgram_frontend

    volumes:
      - frontend_volume:/app/result_build/
      - static:/app/result_build/static/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/
      - media_volume:/usr/share/nginx/html/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
  