version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    # volumes:
    #   - static:/backend_static
    #   - media_volume:/app/media/
      - ../data/:/app/static/data/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile

    volumes:
      - static:/static
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/static/
      - media:/usr/share/nginx/html/media
      - ../docs/:/usr/share/nginx/html/api/docs/
  